src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/components/auth/login/forgot-password/forgot-password.component.html
src/app/components/auth/login/forgot-password/forgot-password.component.spec.ts
src/app/components/auth/login/forgot-password/forgot-password.component.ts
src/app/components/auth/login/login.component.html
src/app/components/auth/login/login.component.scss
src/app/components/auth/login/login.component.spec.ts
src/app/components/auth/login/login.component.ts
src/app/components/contracts/contracts.component.ts
src/app/services/auth/auth.service.spec.ts
src/app/services/auth/auth.service.ts

This PR adds a sign in page which will later be configured to allow or not allow some people to delete some of the items in the list.

Add authentication

---

package-lock.json
package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/components/auth/login/login.component.html
src/app/services/auth/auth.service.ts

This pr adds cookies so that the user can stay signed in on a page reload, he will be signed in until he signs out (no expiration on cookie)

feat: add cookies for reload

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/components/theme-selector/theme-selector.component.html
src/app/components/theme-selector/theme-selector.component.scss
src/app/components/theme-selector/theme-selector.component.ts
src/app/services/luigi-ui/luigi-ui.service.spec.ts
src/app/services/luigi-ui/luigi-ui.service.ts

fixes: #72 
Apply a checkbox in the settings box that removes the header and side nav. It uses a service in case there are going to be other luigi features needed spread out across the application

add luigi option to remove header and side nav

---

src/app/app.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/services/auth/auth.service.ts
src/app/services/luigi-ui/luigi-ui.service.ts

fixes: #72 
This pr will add luigi option in the url query parameters

fix: add query params for luigi

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/components/contracts/contracts.component.html
src/app/components/contracts/contracts.component.ts
src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
src/app/components/contracts/create-contract-modal/create-contract-modal.component.ts
src/app/components/products/create-product-modal/create-product-modal-detailed/create-product-modal-detailed.component.html
src/app/components/products/create-product-modal/create-product-modal-detailed/create-product-modal-detailed.component.ts
src/app/components/products/create-product-modal/create-product-modal.component.html
src/app/components/products/create-product-modal/create-product-modal.component.ts
src/app/components/products/products.component.html
src/app/components/products/products.component.ts
src/app/components/theme-selector/theme-selector.component.html
src/app/components/theme-selector/theme-selector.component.ts
src/app/services/compact/compact.service.spec.ts
src/app/services/compact/compact.service.ts
src/styles.css

fixes: #73 
Creates a compact checkbox which will globally style all fundamental-ngx inputs which allow compact mode
Table will wait for the migration to add compact mode
Also makes the body with flex for responsiveness

feat: add compact mode globally

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/components/contracts/contracts.component.html
src/app/components/contracts/contracts.component.scss
src/app/components/contracts/contracts.component.ts
src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
src/app/components/contracts/create-contract-modal/create-contract-modal.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/products/create-product-modal/create-product-modal.component.html
src/app/components/products/create-product-modal/create-product-modal.component.ts
src/app/components/products/products.component.html
src/app/components/products/products.component.scss
src/app/components/products/products.component.ts
src/app/pipes/snake-case.pipe.spec.ts
src/app/pipes/snake-case.pipe.ts
src/app/services/compact/compact.service.ts
src/app/services/contract-page/contract-page.service.spec.ts
src/app/services/contract-page/contract-page.service.ts
src/app/services/product-page/product-page.service.spec.ts
src/app/services/product-page/product-page.service.ts
src/app/services/product-switch/product-switch.service.spec.ts
src/app/services/product-switch/product-switch.service.ts
src/app/services/products/products.service.ts
src/app/services/side-navigation/side-navigation.model.ts
src/app/services/side-navigation/side-navigation.service.spec.ts
src/app/services/side-navigation/side-navigation.service.ts

Adds services to bring in data from database
adds a scss var for the color of drag and drop for products

feat: add services for data

---

src/app/components/products/products.component.scss
src/app/components/products/products.component.ts

this pr will add fields to the edit modal of the create product

fix: add fields to edit product dialog

---

src/app/app.component.html
src/app/components/confirm-modal/confirm-modal.component.html
src/app/components/confirm-modal/confirm-modal.component.ts
src/app/components/contracts/contracts.component.ts
src/app/components/products/products.component.html
src/app/components/products/products.component.ts
src/app/services/products/products.service.ts
src/app/shared/notification-confirmation/notification-confirmation.component.html
src/app/shared/notification-confirmation/notification-confirmation.component.ts

Add client side authentication to add or delete on both contracts and products
Add a layout grid to a confirm modal
put titlecase pipe on side nav

feat: add client side authenitcation

---

src/app/app.component.ts
src/app/components/contracts/contracts.component.html
src/app/components/contracts/contracts.component.ts
src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
src/app/components/products/create-product-modal/create-product-modal.component.html
src/app/components/products/products.component.html
src/app/components/products/products.component.ts
src/app/pipes/snake-case.pipe.ts
src/app/services/auth/auth.service.ts
src/app/services/contract-page/contract-page.service.ts
src/app/services/contracts/contracts.service.ts
src/app/services/product-page/product-page.service.ts
src/app/services/products/products.service.ts
src/app/shared/notification-confirmation/notification-confirmation.component.html

This pr will
re add all the things that got deleted
change to fundamental gmail firebase
add pagination on contracts page

feat: add pagination & change firebase to fundamental one

---

src/app/components/contracts/contracts.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/products/products.component.html
src/app/components/products/products.component.ts
src/app/services/products/products.service.ts

Add pagination to product component and service
Change pagination to load 5 items per time

feat:add pagination to products

---

src/app/app.module.ts
src/app/components/auth/login/login.component.html
src/app/components/auth/login/login.component.ts
src/app/services/auth/auth.service.ts

Remove the extra files array which ends up putting a boolean instead of file[]

fix: disabled array of files input validation

---

src/app/components/contracts/contracts.component.ts
src/app/services/contracts/contracts.service.ts
src/app/services/products/products.service.ts

This modifies both services to add to the product or contract page arrays which store the names of the contracts and products stored in the pages

fix: add to array of columns

---

src/app/app.component.ts
src/app/components/auth/login/login.component.html
src/app/components/auth/login/login.component.ts
src/app/models/account.model.ts
src/app/services/auth/auth.service.ts

Add first and last name to register form
Add the feature in the auth service to save it in the database

feat: add first and last name for the register form

---

src/app/app.component.ts
src/app/models/account.model.ts
src/app/services/auth/auth.service.ts

Adds a check to make sure the name is proper
Uses the correct database term for first and last name for the account model

fix: charAt(0) error for initials

---

src/app/app.component.ts

Remove debugger in app component

fix: remove debugger

---

src/app/services/contracts/contracts.service.ts
src/app/services/products/products.service.ts

this pr will change the source of firebase retrieval due to the change database api

fix: change source of collection for products and contracts

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/users/users.component.html
src/app/components/users/users.component.scss
src/app/components/users/users.component.spec.ts
src/app/components/users/users.component.ts
src/app/models/account.model.ts
src/app/services/users/users.service.spec.ts
src/app/services/users/users.service.ts

Add users service 
Add user component

Feat add users section

---

src/app/services/auth/auth.service.ts

adds default admin: falt property to profile creation to set the account as admin or not

fix: add admin property to profile creation

---

src/app/components/users/users.component.ts
src/app/services/users/users.service.ts

make the observable of user of type account

fix: make account observable specific type

---

package-lock.json
package.json

migrate to ngx with new table which will add toolbar in a later pr

chore: migrate to ngx rc21.19

---

src/app/services/contracts/contracts.service.ts
src/app/services/products/products.service.ts

Switch the source to modify the arrays shown in the combo boxs

fix: add or remove from contract and page lists

---

.reuse/dep5
LICENSE
NOTICE
README.md

chore: change CLA agreement to DCO

---

package-lock.json
package.json
tsconfig.json

fixes: #262 
allow synthetic imports

chore: fix firebase imports

---

package-lock.json
package.json
src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
src/app/components/products/create-product-modal/create-product-modal.component.html

Migrate the demo app to fundamental-ngx/core 0.23.1
Change the grid to new version of grid

chore: migrate to ngx 0.23.1
